[tool.poetry]
name = "PyKantorovich"
packages = [
    { include = "pykantorovich" },
]
version = "0.2.0"
description = "Kantorovich distance between probabilities on a finite space."
homepage = "https://github.com/stla/PyKantorovich"
authors = ["Stéphane Laurent <laurent_step@outlook.fr>"]
documentation = "https://pykantorovich.readthedocs.io/en/latest/"
keywords = ["Kantorovich distance", "linear programming"]
license = "GPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
numpy = "^1.21.2"
pycddlib = "^2.1.4"
scipy = "^1.7.1"
cvxpy = "^1.1.17"
sphinx = { version = "^5.3.0", optional = true }
sphinx-rtd-theme = { version = "^1.1.1", optional = true }
sphinxcontrib-napoleon = { version = "^0.7", optional = true }
sphinxcontrib-restbuilder = { version = "^0.3", optional = true }

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon", "sphinxcontrib-restbuilder"]

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
